const Datas=[
  
   
    {
      "id": 5,
      "title": "Aurora Sparkle Solitaire Ring",
      "price": 128363,
      "detail":"Set in 18 KT Yellow Gold(5.040 g) with diamonds (0.598 ct ,IJ-SI)",
      "description": "Gold",
      "Dimensions":"Width : 11.00 mm" ,
       "dimensions":"Height : 3.5 mm" ,           
      "weight":"Gross : 5.160 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 20",
      "TotalWeight":"0.348 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/S/R/SR03897-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/S/R/SR03897-YGP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/S/R/SR03897-YGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/S/R/SR03897-YGP900_5_lar.jpg",
        "rate": 4.6,
     
    },
    {
      "id": 6,
      "title": "Halo Bliss Solitaire Ring",
      "price": 123868,
      "detail":"Set in 18 KT Yellow Gold(3.450 g) with diamonds (0.744 ct ,IJ-SI)",
      "description": "Gold",
      "Dimensions":"Width : 12.80 mn" ,
       "dimensions":"Height : 4.85 mm" ,           
      "weight":"Gross : 3.599 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 44",
      "TotalWeight":"0.744 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/S/R/SR03900-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/S/R/SR03900-YGP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/S/R/SR03900-YGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/S/R/SR03900-YGP900_5_lar.jpg",
        "rate": 3.9,
      
    },
    {
      "id": 7,
      "title": "Helina Spiral Diamond Ring",
      "price": 180622 ,
      "detail":"Set in 18 KT Rose Gold(2.850 g) with diamonds (0.150 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":"Width : 15.80 mm" ,
       "dimensions":"Height : 4.3 mm" ,           
      "weight":" Gross : 3.210 g",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"FG-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 22",
      "TotalWeight":"0.150 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/R/JR08560-RGS300_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/R/JR08560-RGS300_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/R/JR08560-RGS300_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/R/JR08560-RGS300_6_lar.jpg",
       "rate": 3.2,
       
    },
    {
      "id": 8,
      "title": "Luminary Diamond Band ring",
      "price": 379509 ,
      "detail":"Set in 14 KT Yellow Gold(2.840 g) with diamonds (0.203 ct ,IJ-SI)",
      "description": "Gold",
      "Dimensions":"Width : 8.83 mm" ,
       "dimensions":"Height : 3.11 mm" ,           
      "weight":" Gross : 2.881 g",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 53",
      "TotalWeight":"0.203 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/R/JR08091-1YP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/R/JR08091-1YP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/R/JR08091-1YP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/R/JR08091-1YP900_6_lar.jpg",
     "rate": 4.2
    },
    {
      "id": 9,
      "title": "Brea Florence Diamond Ring",
      "price": 256291 ,
      
      "detail":"Set in 14 KT Rose Gold(3.260 g) with diamonds (0.224 ct ,IJ-SI)",
      "description": "Gold",
      "Dimensions":"Width : 13.65 mm" ,
       "dimensions":"Height : 8.5 mm" ,           
      "weight":"Gross : 3.305 g ",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 37",
      "TotalWeight":"0.224 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/R/JR06662-1RP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/R/JR06662-1RP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/R/JR06662-1RP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/R/JR06662-1RP900_6_lar.jpg",
      "rate": 3.2,
    },
    {
      "id": 10,
      "title": "Cia Petal Overlapped Diamond Band Ring",
      "price": 297919 ,
      
      "detail":"Set in 14 KT Yellow Gold(2.110 g) with diamonds (0.235 ct ,GH-VS)",
      "description": "Gold",
      "Dimensions":"Width : 6.5 mm" ,
       "dimensions":"Height : 2.9 mm" ,           
      "weight":" Gross : 2.157 g",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"GH-VS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 36",
      "TotalWeight":"0.235 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/R/JR03514-YGP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03514-YGP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03514-YGP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03514-YGP600_6_lar.jpg",
      "rate": 4.2
    },
     {
      "id": 1,
      "title": "Solitary Sparkle 73 Cuts Solitaire Ring",
      "price": 419287 ,
      "detail":"Set in 18 KT Yellow Gold(3.440 g) with diamonds (1.000 ct ,IJ-SI)",
      "description": "Gold",
      "Dimensions":"Width : 7.60 mm" ,
       "dimensions":"Height : 6.5 mm" ,           
      "weight":" Gross : 3.640 g",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 1",
      "TotalWeight":"1.000 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/S/R/SR04123-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/S/R/SR04123-YGP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/S/R/SR04123-YGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/S/R/SR04123-YGP900_5_lar.jpg",
        "rate": 4.6,
       
      
    },
    
    {
      "id": 2,
      "title": "Triumph Solitaire Ring",
      "price": 183490 ,
      "detail":"Introducing the Triumph Solitaire Ring, a stunning piece of jewellery that is sure to turn heads. This two-tone gold ring features a sparkling solitaire gemstone that is sure to catch the eye. The elegant design is perfect for any occasion, and the comfortable, secure fit ensures that this ring will stay in place all day long. Whether you're dressing up for a special event or simply adding a touch of glamour to your everyday look, the Triumph Solitaire Ring is a must-have addition to any jewellery collection.",
      "description": "Gold",
      "Dimensions":"Width : 9.6 mm" ,
       "dimensions":"Height : 5.2 mm" ,           
      "weight":"Gross : 2.738 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 24",
      "TotalWeight":"0.500 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/S/R/SR02841-WRP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/S/R/SR02841-WRP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/S/R/SR02841-WRP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/S/R/SR02841-WRP900_6_lar.jpg",
        "rate": 3.9,
       
    },
    {
      "id": 3,
      "title": "Floret Mesh Diamond Ring",
      "price": 170984 ,
      "detail":"Embrace the essence of floral elegance with the Floret Mesh Diamond Ring. This exquisite piece showcases a mesmerizing array of round-cut diamonds intricately set in a rose gold lattice, forming a stunning floral pattern. Each diamond petal glistens with unparalleled brilliance, creating a captivating interplay of light and sparkle. Perfect for special occasions or to add a touch of luxury to your everyday ensemble, this ring is a true testament to timeless beauty and craftsmanship.",
      "description": "Gold",
      "Dimensions":"Width : 20.1 mm" ,
       "dimensions":"Height : 5.8 mm" ,           
      "weight":"Gross : 5.415 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"GH-SI",
      "Setting":"Setting : Plate Prong",
       "Total" : "Total No. : 91",
      "TotalWeight":"0.974 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/R/JR03804-RGP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03804-RGP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03804-RGP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03804-RGP600_5_lar.jpg",
        "rate": 3.4,
    },
        
    {
      "id": 4,
      "title": "Lura Halo Diamond Ring",
      "price":183570  ,
      "detail":"Set in 18 KT White Gold(4.960 g) with diamonds (0.886 ct ,GH-SI)",
      "description": "Gold",
      "Dimensions":"Width : 7.17 mm" ,
       "dimensions":"Height : 20.84 mm" ,           
      "weight":"Gross : 5.137 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"GH-SI",
      "Setting":"Setting : Plate Prong",
       "Total" : "Total No. : 65",
      "TotalWeight":"0.886 ct",
      "category": "rings",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/R/JR03066-WGP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03066-WGP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03066-WGP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/R/JR03066-WGP600_6_lar.jpg",
        "rate": 4.9,
    },
    {
      "id":11,
      "title": "Sameera Diamond Necklace",
      "price":162504,
      "detail":"Set in 14 KT Rose Gold(11.240 g) with diamonds (0.445 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":"Length : 43.18cm (17 inches)" ,
       "dimensions":"Height : 20.75 mm" ,           
      "weight":" Gross : 11.329 g",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"FG-SI",
      "Setting":"Setting : Micro",
       "Total" : "Total No. : 70",
      "TotalWeight":"0.445 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL04362-RGS300_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04362-RGS300_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04362-RGS300_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04362-RGS300_5_lar.jpg",
       "rate": 4.2
    },
    {
      "id": 12,
      "title": "Evana Diamond Necklace",
      "price": 289389 ,
      "detail":"Set in 14 KT Yellow Gold(9.880 g) with diamonds (0.457 ct ,GH-SI)",
      "description": "Gold",
      "Dimensions":"Length : 43.18cm (17 inches)" ,
       "dimensions":"Height : 9.5 mm" ,           
      "weight":" Gross : 9.971 g",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"GH-SI",
      "Setting":"Setting : Split Prong",
       "Total" : "Total No. : 70",
      "TotalWeight":"0.457 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL04421-1YP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04421-1YP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04421-1YP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04421-1YP600_5_lar.jpg",
    "rate": 4.2
    },
    {
      "id": 13,
      "title": "Lupine Wood Grain Diamond Necklace",
      "price": 544555 ,
      "detail":"Embrace the beauty of nature with the Lupine Wood Grain Diamond Necklace by CaratLane. This stunning necklace captures the essence of natural elements with its wood grain-inspired design. The pendant features a textured pattern resembling the delicate grains of wood, meticulously crafted in gold. The pendant is adorned with dazzling diamonds that add a touch of sparkle and brilliance. The pendant hangs from a slender gold chain, allowing it to gracefully rest on your neckline Necklace available only in 18 Inch",
      "description": "Gold",
      "Dimensions":"Length : 45.72cm (18 inches)" ,
       "dimensions":"Height : 37.6 mm" ,           
      "weight":"Gross : 7.534 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 56",
      "TotalWeight":"0.520 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL03298-RGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL03298-RGP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL03298-RGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL03298-RGP900_6_lar.jpg",
     "rate": 4.2
    },
    {
      "id": 14,
      "title": "Gleam Stardust Diamond Necklace",
      "price": 313002 ,
      "detail":"Set in 18 KT Rose Gold(8.860 g) with diamonds (0.406 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":"Length : 43.18cm (17 inches)" ,
       "dimensions":"Height : 28 mm" ,           
      "weight":" Gross : 8.941 g",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"FG-SI",
      "Setting":"Setting : Micro Prong",
       "Total" : "Total No. : 78",
      "TotalWeight":"0.406 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL04423-1YP900_1_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04423-1YP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04423-1YP900_3_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04423-1YP900_5_lar.jpg",
     "rate": 4.2,
      
    },
    {
      "id": 15,
      "title": "Arina Diamond Necklace",
      "price": 378233 ,
      "detail":"Set in 18 KT Yellow Gold(15.390 g) with diamonds (1.283 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":"Length : 45.72cm (18 inches)" ,
       "dimensions":"Height : 29 mm" ,           
      "weight":"Gross : 15.647 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"FG-SI",
      "Setting":"Setting : Nick",
       "Total" : "Total No. : 133",
      "TotalWeight":"1.283 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL04352-YGS300_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04352-YGS300_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04352-YGS300_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04352-YGS300_7_lar.jpg",
     "rate": 4.2
    },
    {
      "id": 16,
      "title": "Noyal Diamond Necklace",
      "price": 339232 ,
      "detail":"Set in 14 KT Rose Gold(15.530 g) with diamonds (1.642 ct ,IJ-SI)",
      "description": "Gold",
      "Dimensions":"Length : 43.18cm (17 inches)" ,
       "dimensions":"Height : 20.7 mm" ,           
      "weight":"Gross : 15.858 g ",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"Total No. : 353",
      "Setting":"Setting : Micro Prong",
       "Total" : "Total No. : 353",
      "TotalWeight":"1.642 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL05113-1RP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL05113-1RP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL05113-1RP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL05113-1RP900_6_lar.jpg",
      "rate":"4.8",
    },
    {
      "id": 17,
      "title": "Mei Diamond Necklace",
      "price": 493909 ,
      "detail":"Set in 18 KT Rose Gold(23.990 g) with diamonds (1.845 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":"Length : 40.64cm (16 inches)" ,
       "dimensions":"Height : 4.65 mm" ,           
      "weight":" Gross : 24.359 g",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"FG-SI",
      "Setting":"Setting : Miraculas Prong",
       "Total" : "Total No. : 37",
      "TotalWeight":"1.845 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL05516-RGS300_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL05516-RGS300_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL05516-RGS300_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL05516-RGS300_5_lar.jpg",
      "rate":"3.9"
    },
    {
      "id": 18,
      "title": "Linear Floret Two Row Diamond Necklace",
      "price": 520821,
      "detail":"Set in 14 KT Yellow Gold(13.240 g) with diamonds (2.345 ct ,GH-VS)",
      "description": "Gold",
      "Dimensions":"Length : 40.64cm (16 inches)" ,
       "dimensions":"Height : 5.1 mm" ,           
      "weight":"Gross : 13.709 g ",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"GH-VS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 272",
      "TotalWeight":"2.345 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL03317-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL03317-YGP900_2_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL03317-YGP900_5_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL03317-YGP900_4_lar.jpg",
      "rate": 4.2
      
    },
    {
      "id": 19,
      "title": "Ivy Leaf Diamond Necklace",
      "price": 383822,
      "detail":"Set in 18 KT White Gold(14.440 g) with diamonds (1.250 ct ,GH-VS)",
      "description": "Gold",
      "Dimensions":"Length : 40.64cm (16 inches)" ,
       "dimensions":"Height : 27.85 mm" ,           
      "weight":" Gross : 14.690 g",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"GH-VS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 171",
      "TotalWeight":"1.250 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL00228-WGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL00228-WGP900_2_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL00228-WGP900_3_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL00228-WGP900_4_lar.jpg",
     "rate": 3.2,
    },
    {
      "id": 20,
      "title": "Yasmin Diamond Necklace",
      "price": 482892,
      "detail":"Set in 14 KT Yellow Gold(6.280 g) with diamonds (0.587 ct ,IJ-SI)",
      "description": "Gold",
      "Dimensions":"Length : 43.18cm (17 inches)" ,
       "dimensions":"Height : 12.3 mm" ,           
      "weight":" Gross : 6.443 g",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Micro Prong",
       "Total" : "Total No. : 79",
      "TotalWeight":"0.587 ct",
      "category": "necklace",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/L/JL04471-1YP9P0_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04471-1YP9P0_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04471-1YP9P0_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/L/JL04471-1YP9P0_6_lar.jpg",
      "rate": 4.2
    },
     {
      "id": 25,
      "title": "Oshin Diamond Bracelet",
      "price": 137382,
      "detail":"Set in 14 KT Yellow Gold(6.070 g) with diamonds (0.370 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":"Length : 17.78cm (7.25 inches)" ,
       "dimensions":"Height : 6.6 mm" ,           
      "weight":"Gross : 6.144 g ",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"FG-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 55",
      "TotalWeight":"0.370 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT01605-YGS300_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT01605-YGS300_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT01605-YGS300_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT01605-YGS300_5_lar.jpg",
      "rate": 4.2
    },
    {
      "id": 26,
      "title": "Kissing Heart Diamond Bracelet",
      "price": 121323,
      "detail":"Set in 18 KT Yellow Gold(2.940 g) with diamonds (0.140 ct ,EF-VVS)",
      "description": "Gold",
      "Dimensions":"Length : 17.78cm (7 inches)" ,
       "dimensions":"Height : 3.7 mm" ,           
      "weight":"Gross : 2.968 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"EF-VVS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 28",
      "TotalWeight":"0.140 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT00075-YGP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00075-YGP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00075-YGP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00075-YGP600_5_lar.jpg",
      "rate":3.5,
      
    },
    {
      "id": 27,
      "title": "Diamond Butterfly Charm Bracelet",
      "price":143780,
      "detail":"Adorn your wrist with the enchanting beauty of CaratLane's Diamond Butterfly Charm Bracelet. This exquisite piece, set in lustrous yellow gold, features a delicate butterfly charm, meticulously adorned with sparkling diamonds, symbolizing transformation and grace. Its elegant design makes it a versatile accessory, perfect for both casual and formal occasions. Ideal for those who appreciate the delicate beauty of nature and the timeless elegance of diamonds, this bracelet serves as a reminder of personal growth and the beauty of change.",
      "description": "Gold",
      "Dimensions":"Length : 17.78cm (7.25 inches)" ,
       "dimensions":"Height : 5.75 mm" ,           
      "weight":" Gross : 2.537 g",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Bezel",
       "Total" : "Total No. : 10",
      "TotalWeight":"0.086 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT00603-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00603-YGP900_5_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00603-YGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00603-YGP900_8_lar.jpg",
      "rate":4.5,
    },
      {
      "id": 30,
      "title": "Charmi Circlet Diamond Bracelet",
      "price": 489239,
      "detail":"The Charmi Circlet Diamond Bracelet is a testament to timeless elegance, set in lustrous rose gold with a dazzling array of diamonds. This piece effortlessly combines classic charm with contemporary design, making it a versatile addition to any jewellery collection. Its circlet motif symbolizes eternity and unity, offering a meaningful touch to its wearer. Ideal for both special occasions and everyday wear, it brings a subtle sparkle and sophistication to any ensemble.",
      "description": "Gold",
      "Dimensions":"Length : 17.78cm (7.25 inches)" ,
       "dimensions":"Height : 10.75 mm" ,           
      "weight":"Gross : 7.478 g ",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Split Prong",
       "Total" : "Total No. : 42",
      "TotalWeight":"0.290 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT01769-1RP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT01769-1RP900_5_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT01769-1RP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT01769-1RP900_6_lar.jpg",
        "rate": 4.2
      
    },
    {
      "id": 21,
      "title": "Reneta Diamond Tennis Bracelet",
      "price": 343132,
      "detail":"Set in 18 KT Yellow Gold(15.140 g) with diamonds (2.025 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":"Length : 17.78cm (7 inches)" ,
       "dimensions":"Height : 4.4 mm" ,           
      "weight":"Gross : 15.545 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"FG-SI",
      "Setting":"Setting : Miraculas Prong",
       "Total" : "Total No. : 36",
      "TotalWeight":"2.025 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT02789-YGS300_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT02789-YGS300_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT02789-YGS300_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT02789-YGS300_6_lar.jpg",
      "rate":"3.5",
    },
    {
      "id": 22,
      "title": "Alba Diamond Tennis Bracelet",
      "price": 478983,
      "detail":"Set in 18 KT Rose Gold(13.230 g) with diamonds (2.047 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":"Length : 17.78cm (7 inches)" ,
       "dimensions":"Height : 3.4 mm" ,           
      "weight":"Gross : 13.639 g ",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"FG-SI",
      "Setting":"Setting : Miraculas Prong",
       "Total" : "Total No. : 26",
      "TotalWeight":"2.047 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT02790-RGS300_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT02790-RGS300_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT02790-RGS300_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT02790-RGS300_6_lar.jpg",
      "rate":"3.5",
      
    },
    {
      "id": 23,
      "title": "Ahana Seven Stone Adjustable Diamond Bracelet",
      "price": 129378,
      "detail":"Set in 18 KT Yellow Gold(5.170 g) with diamonds (0.628 ct ,GH-VS)",
      "description": "Gold",
      "Dimensions":"Length : 22.86cm (9 inches)" ,
       "dimensions":"Height : 4 mm" ,           
      "weight":" Gross : 5.296 g",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"GH-VS",
      "Setting":"Setting : Plate Prong",
       "Total" : "Total No. : 81",
      "TotalWeight":"0.628 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT00329-YGP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00329-YGP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00329-YGP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00329-YGP600_6_lar.jpg",
      
      "rate": 4.2
    },
    {
      "id": 24,
      "title": "Amour Diamond Bracelet",
      "price": 139870,
      "detail":"Set in 18 KT Rose Gold(7.130 g) with diamonds (0.337 ct ,GH-VS)",
      "description": "Gold",
      "Dimensions":"Length : 58.74mm (2.5 Anna)" ,
       "dimensions":"Height : 2.62 mm" ,           
      "weight":" Gross : 7.197 g",
      "Purity":"18 KT",
      "Diamond":"Diamond",
      "Type":"GH-VS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 84",
      "TotalWeight":"0.337 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT00318-RGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00318-RGP900_6_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00318-RGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00318-RGP900_5_lar.jpg",
     
     "rate": 3.2,
    },
   
    {
      "id": 28,
      "title": "Elegant Knot Diamond Bracelet",
      "price": 224897,
      "detail":"Set in 14 KT Yellow Gold(7.106 g) with diamonds (0.421 ct ,IJ-SI)",
      "description": "Gold",
      "Dimensions":"Length : 57.15mm (2.4 Anna)" ,
       "dimensions":"Height : 10.73 mm" ,           
      "weight":"Gross : 7.190 g ",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Plate Prong",
       "Total" : "Total No. : 47",
      "TotalWeight":"0.421 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT00191-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00191-YGP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00191-YGP900_6_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00191-YGP900_5_lar.jpg",
        "rate": 4.2
    },
    {
      "id": 29,
      "title": "Flare Twill Diamond Bracelet",
      "price": 223192,
      "detail":"Set in 14 KT Rose Gold(16.590 g) with diamonds (0.300 ct ,EF-VVS)",
      "description": "Gold",
      "Dimensions":"Length : 57.15mm (2.4 Anna)" ,
       "dimensions":"Height : 6.6 mm" ,           
      "weight":" Gross : 16.650 g",
      "Purity":"14 KT",
      "Diamond":"Diamond",
      "Type":"EF-VVS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 21",
      "TotalWeight":"0.300 ct",
      "category": "bracelet",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/T/JT00659-RGP600_2_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00659-RGP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00659-RGP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/T/JT00659-RGP600_5_lar.jpg",
       "rate": 3.2,
    },
  
    {
      "id": 31,
      "title": "Plumeria Cluster Diamond Stud Earrings",
      "price": 196971,
      "detail":"These stunning Plumeria Cluster Diamond Stud Earrings are the perfect addition to any jewellery collection. Crafted with 18Kt gold, these earrings feature a cluster of dazzling diamonds with a plumeria design. The perfect combination of sparkle and sophistication, these earrings will be sure to make a statement. Perfect for a special occasion or just as an everyday reminder of your beauty, these diamond and gold stud earrings are sure to become your favorite accessory! With their friendly, timeless design, these earrings are sure to be cherished for years to come. ",
      "description": "Gold",
      "Dimensions":" Width : 24.13 mm" ,
       "dimensions":"Height : 24.68 mm" ,           
      "weight":"Gross : 14.768 g ",
      "Purity":" 18 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 22",
      "TotalWeight":"0.340 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE02774-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE02774-YGP900_6_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE02774-YGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE02774-YGP900_3_lar.jpg",
      "rate":"4.0"
    },
     {
      "id": 39,
      "title": "Alder Root Diamond Stud Earrings",
      "price": 103363,
     "detail":"These Alder Root Diamond Stud Earrings by CaratLane are a stunning addition to any outfit! Crafted with a modern, minimal design, these earrings feature a 0.41 ct diamond set in 18KT yellow gold. They're perfect for adding sparkle to any look, while also being subtle and sophisticated. With their timeless appeal and friendly price, these earrings make a great gift for any special occasion. Treat yourself or someone special to these beautiful diamond and gold stud earrings, and add a touch of elegance to your wardrobe.",
      "description": "Gold",
      "Dimensions":" Width :  14.6 mm" ,
       "dimensions":"Height : 23.2 mm" ,           
      "weight":" Gross : 4.722 g",
      "Purity":" 18 KT",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 42",
      "TotalWeight":"0.410 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE04221-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04221-YGP900_6_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04221-YGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04221-YGP900_5_lar.jpg",
      "rate": 3.2,
    },
    {
      "id": 35,
      "title": "Bahar Diamond Jhumkas",
      "price":146405,
      "detail":" Bahar Diamond Earrings offer a delicate design adorned with sparkling diamonds. Crafted from premium materials, they provide a refined look, perfect for formal events or special occasions. The floral motif adds depth and movement, creating a dynamic appearance. Lightweight and comfortable, they are designed for easy wear, with secure closures ensuring a reliable fit. The versatile design makes them suitable for various outfits, adding a touch of sophistication.",
      "description": "Gold",
      "Dimensions":"Width : 17.4 mm " ,
       "dimensions":"Height : 28.5 mm" ,           
      "weight":" Gross : 11.150 g",
      "Purity":" 14 KT",
      "Diamond":"Diamond",
      "Type":"GH-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 62",
      "TotalWeight":"0.400 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE08327-1YP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE08327-1YP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE08327-1YP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE08327-1YP600_7_lar.jpg",
      "rate": 4.2
    },
    {
      "id": 36,
      "title": "Shifa Gemstone Jhumkas",
      "price": 144952,
      "detail":"Shifa Gemstone Earrings feature a vibrant design adorned with colorful gemstones. Crafted from premium materials, they provide a refined look, perfect for formal events or special occasions. The intricate design adds depth and movement, creating a dynamic appearance. Lightweight and comfortable, they are designed for easy wear, with secure closures ensuring a reliable fit. ",
      "description": "Gold",
      "Dimensions":"Width : 21.45 mm " ,
       "dimensions":"Height : 34.35 mm" ,           
      "weight":"Gross : 10.562 g ",
      "Purity":" 14 KT",
      "Diamond":"Diamond",
      "Type":"GH-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 78",
      "TotalWeight":"0.460 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE08331-1YP6P0_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE08331-1YP6P0_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE08331-1YP6P0_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE08331-1YP6P0_7_lar.jpg",
      "rate":"4.2"
     
    },
    {
      "id": 32,
      "title": "Carina Diamond Hoop Earrings",
      "price":163348,
      "detail":" Set in 18 KT Rose Gold(5.010 g) with diamonds (1.004 ct ,GH-SI)",
      "description": "Gold",
      "Dimensions":"Width : 12.7 mm " ,
       "dimensions":"Height : 16.3 mm" ,           
      "weight":"Gross : 5.211 g ",
      "Purity":" 18 KT",
      "Diamond":"Diamond",
      "Type":"GH-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 118",
      "TotalWeight":"1.004 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE04023-RGP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04023-RGP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04023-RGP600_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04023-RGP600_6_lar.jpg",
      "rate":"4.9"
    },
    {
      "id": 33,
      "title": "Round Stunning Diamond Earring",
      "price": 156653,
      "detail":" These earrings, set in 18 KT White Gold, feature solitaire diamonds that radiate a classic and sophisticated look. Perfect for special occasions or adding a touch of sparkle to your everyday style, these earrings are not just accessories; they're a symbol of enduring beauty. The Vibrant Solitaire Stud Earrings are a must-have for those who appreciate the finer things in life.",
      "description": "Silver",
      "Dimensions":" Width : 5.5 mm" ,
       "dimensions":"Height : 6 mm" ,           
      "weight":"Gross : 1.990 g ",
      "Purity":"18 KT ",
      "Diamond":"Diamond",
      "Type":"IJ-SI",
      "Setting":"Setting : Prong",
       "Total" : "0.800 ct",
      "TotalWeight":"",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/S/E/SE00332-WGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/S/E/SE00332-WGP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/S/E/SE00332-WGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/S/E/SE00332-WGP900_6_lar.jpg",
     "rate": 4.2
    },
    {
      "id": 34,
      "title": "Lillian Diamond Stud Earrings",
      "price":142373,
      "detail":" Set in 18 KT Yellow Gold(7.310 g) with diamonds (0.400 ct ,GH-VS)",
      "description": "Gold",
      "Dimensions":"Width : 18.2 mm " ,
       "dimensions":"Height : 18 mm" ,           
      "weight":" Gross : 7.390 g",
      "Purity":" 18 KT",
      "Diamond":"Diamond",
      "Type":"GH-VS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 42",
      "TotalWeight":"0.400 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE04721-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04721-YGP900_2_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04721-YGP900_5_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04721-YGP900_7_lar.jpg",
      "rate": 3.2,
      
    },
    
    {
      "id": 37,
      "title": "Blossom Chandelier Diamond Drop Earrings",
      "price": 199561,
      "detail":" Set in 18 KT Yellow Gold(9.350 g) with diamonds (0.629 ct ,GH-VS)",
      "description": "Gold",
      "Dimensions":" Width : 16.9 mm" ,
       "dimensions":"Height : 51.3 mm" ,           
      "weight":"Gross : 9.476 g ",
      "Purity":"18 KT ",
      "Diamond":"Diamond",
      "Type":"GH-VS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 80",
      "TotalWeight":"0.629 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE04979-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04979-YGP900_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04979-YGP900_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04979-YGP900_5_lar.jpg",
      "rate": 4.2
    },
    {
      "id": 38,
      "title": "Circular Stark Diamond Stud Earrings",
      "price": 210077,
      "detail":" Illuminate your look with the Circular Stark Diamond Stud Earrings from CaratLane. These earrings showcase diamonds intricately set in a circular design, exuding a sense of timeless allure and sophistication. Each diamond is handpicked and cut to boost its shine, elevating these elegant earrings. With their captivating circular motif and sparkling allure, these earrings are a symbol of refined taste and elegant style, making them a perfect accessory to enhance your looks and add glamour.",
      "description": "Gold",
      "Dimensions":" Width : 16.5 mm" ,
       "dimensions":"Height : 16.5 mm" ,           
      "weight":" Gross : 7.684 g",
      "Purity":" 18 KT",
      "Diamond":"Diamond",
      "Type":"GH-SI",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 208",
      "TotalWeight":"1.222 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE04303-YGP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04303-YGP600_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04303-YGP600_2_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE04303-YGP600_5_lar.jpg",
     "rate": 4.2
      
    },
   
    {
      "id": 40,
      "title": "Delicate Dewdrop Diamond Stud Earrings",
      "price": 39960 ,
      "detail":"Set in 14 KT Rose Gold(2.010 g) with diamonds (0.167 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":" Width : 6.3 mm" ,
       "dimensions":"Height : 8.3 mm" ,           
      "weight":" Gross : 1.545 g",
      "Purity":" 14 KT",
      "Diamond":"Diamond",
      "Type":"EF-VVS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 42",
      "TotalWeight":"0.174 ct",
      "category": "earring",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/E/JE06095-RGS300_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/E/JE06095-RGS300_4_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/E/JE06095-RGS300_6_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/E/JE06095-RGS300_3_lar.jpg",
      "rate": 4.2

    },
      {
      "id": 41,
      "title": "Glowing Symphony 22KT Gold Bangle",
      "price": 139960 ,
      "detail":"Set in 22 KT Yellow Gold(15.450 g)",
      "description": "Gold",
      "Dimensions":" Width : 13mm" ,
       "dimensions":"Height : 5.5 mm" ,           
      "weight":" Gross : 1.545 g",
      "Purity":" 14 KT",
      "Diamond":"Diamond",
      "Type":"EF-VVS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 42",
      "TotalWeight":"0.174 ct",
      "category": "bangles",
      "image": "https://cdn.caratlane.com/media/catalog/product/K/B/KB00851-2Y0000_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/K/B/KB00851-2Y0000_3_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/K/B/KB00851-2Y0000_4_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/K/B/KB00851-2Y0000_5_lar.jpg",
      "rate": 4.2

    },
       {
      "id": 42,
      "title": "Delicate Dewdrop Diamond Stud Earrings",
      "price": 39960 ,
      "detail":"Set in 14 KT Rose Gold(2.010 g) with diamonds (0.167 ct ,FG-SI)",
      "description": "Gold",
      "Dimensions":" Width : 6.3 mm" ,
       "dimensions":"Height : 8.3 mm" ,           
      "weight":" Gross : 1.545 g",
      "Purity":" 14 KT",
      "Diamond":"Diamond",
      "Type":"EF-VVS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 42",
      "TotalWeight":"0.174 ct",
      "category": "bangles",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/B/JB00239-YGP900_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/B/JB00239-YGP900_4_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/B/JB00239-YGP900_3_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/B/JB00239-YGP900_5_lar.jpg",
      "rate": 4.2

    },
      {
      "id": 43,
      "title": "Glowing Symphony 22KT Gold Bangle",
      "price": 139960 ,
      "detail":"Set in 22 KT Yellow Gold(15.450 g)",
      "description": "Gold",
      "Dimensions":" Width : 13mm" ,
       "dimensions":"Height : 5.5 mm" ,           
      "weight":" Gross : 1.545 g",
      "Purity":" 14 KT",
      "Diamond":"Diamond",
      "Type":"EF-VVS",
      "Setting":"Setting : Prong",
       "Total" : "Total No. : 42",
      "TotalWeight":"0.174 ct",
      "category": "bangles",
      "image": "https://cdn.caratlane.com/media/catalog/product/J/B/JB00803-YGP600_1_lar.jpg",
      "imge":"https://cdn.caratlane.com/media/catalog/product/J/B/JB00803-YGP600_4_lar.jpg",
      "im":"https://cdn.caratlane.com/media/catalog/product/J/B/JB00803-YGP600_3_lar.jpg",
      "img":"https://cdn.caratlane.com/media/catalog/product/J/B/JB00803-YGP600_5_lar.jpg",
      "rate": 4.2

    },
  ]

export default Datas